# Generated by Django 3.2.6 on 2021-08-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0006_alter_preguntasrespondidas_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('HISTORIA', 'Historia'), ('GEOGRAFIA', 'Geografía'), ('EDUCACION', 'Educación'), ('ECONOMIA', 'Economía'), ('CULTURA', 'Cultura')], default='', max_length=50),
        ),
    ]
