# Generated by Django 3.2.6 on 2021-08-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0007_pregunta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('HISTORIA', 'Historia'), ('GEOGRAFIA', 'Geografía'), ('EDUCACION', 'Educación'), ('ECONOMIA', 'Economía'), ('CULTURA', 'Cultura'), ('DEPORTE', 'Deporte')], default='', max_length=50),
        ),
    ]
