# Generated by Django 3.2.6 on 2021-08-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0008_alter_pregunta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='nivel',
            field=models.CharField(choices=[('FACIL', 'Facil'), ('MEDIO', 'Medio'), ('DIFICIL', 'Dificil')], default='', max_length=50),
        ),
    ]
