# Generated by Django 3.2.6 on 2021-09-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0009_pregunta_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='nivel',
            field=models.CharField(default='', max_length=10, verbose_name='nivel'),
        ),
    ]
